# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180712_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
