# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180712_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
