# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180713_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
